# Generated by Django 4.1.4 on 2022-12-30 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 35, 52, 724563, tzinfo=datetime.timezone.utc)),
        ),
    ]
