# Generated by Django 4.1.4 on 2022-12-30 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0003_otpmanagement_alter_useraccount_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmanagement',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 2, 21, 207089, tzinfo=datetime.timezone.utc)),
        ),
    ]
