# Generated by Django 4.1.4 on 2022-12-30 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0004_otpmanagement_otp_alter_useraccount_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 15, 30, 529270, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 14, 10, 30, 509303, tzinfo=datetime.timezone.utc)),
        ),
    ]
