# Generated by Django 4.1.4 on 2023-01-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0005_otpmanagement_expireat_alter_useraccount_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(),
        ),
    ]
