# Generated by Django 4.1.4 on 2023-01-01 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0006_delete_useraccount_alter_otpmanagement_expireat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(db_column='accountID', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
    ]
