# Generated by Django 4.1.4 on 2023-01-02 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0007_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 7, 10, 47, 14368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
