# Generated by Django 4.1.4 on 2023-01-31 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0009_alter_otpmanagement_expireat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteEvent',
            fields=[
                ('eventNo', models.BigAutoField(primary_key=True, serialize=False)),
                ('eventTitle', models.BinaryField()),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('eventQuestion', models.BinaryField()),
                ('status', models.CharField(default='PC', max_length=2)),
                ('publicKey', models.TextField(default='NOT APPLICABLE')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default='NOT APPLICABLE', max_length=64)),
                ('eventNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.voteevent')),
            ],
        ),
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 4, 29, 18, 412709, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='VotingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castedVote', models.TextField(default='NOT APPLICABLE')),
                ('eventNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.voteevent')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.voter')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteOption', models.BinaryField()),
                ('voteEncoding', models.TextField(default=0)),
                ('voteTotalCount', models.TextField(default=0)),
                ('eventNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.voteevent')),
            ],
        ),
    ]
