# Generated by Django 4.1.4 on 2023-01-31 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0010_voteevent_voter_alter_otpmanagement_expireat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 4, 31, 52, 894675, tzinfo=datetime.timezone.utc)),
        ),
    ]
