# Generated by Django 4.1.4 on 2023-01-31 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0011_alter_otpmanagement_expireat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 4, 34, 1, 791349, tzinfo=datetime.timezone.utc)),
        ),
    ]
