# Generated by Django 4.1.4 on 2023-01-04 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0012_alter_otpmanagement_expireat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmanagement',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 9, 13, 51, 485272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voteevent',
            name='seqNo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
